<?php

use App\Models\Race;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('races', function (Blueprint $table) {
            $table->uuid('id')->primary()->default(Str::uuid());
            $table->string('name', 191);
            $table->text('description');
            $table->text('example_surname');

        });
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Elfe',
            'description' => '<p>Les elfes sont un peuple à la grâce surnaturelle. Ils vivent dans un monde dont ils ne font pas entièrement partie. Ils résident en des lieux à la beauté éthérée, au cœur d\'antiques forêts ou dans des tours d\'argent luisant d\'un éclat féerique, là où une douce musique flotte dans les airs et une brise parfumée enchante les narines. Les elfes aiment la nature et la magie, les arts et le talent artistique, la musique et la poésie.</p><p>Les elfes peuvent vivre plus de 700 ans. Ils sont plus souvent amusés que passionnés et plus facilement curieux qu\'avides. Ils restent à l\'écart et impassibles devant les événements mineurs. Ils comptent sur la diplomatie et les compromis pour résoudre leurs différends avant de recourir à la violence.</p><p>La plupart des elfes résident dans de petits villages forestiers dissimulés parmi les arbres. Ils limitent les contacts avec les étrangers, bien que quelques elfes gagnent très bien leur vie en échangeant des objets manufacturés contre des métaux (que les elfes n\'ont aucune envie d\'extraire).</p>',
            'example_surname' => '<p>Un elfe est considéré comme enfant jusqu\'à ce qu\'il se déclare comme adulte, ce qui arrive un peu après son premier siècle. Avant cela, on le désigne par son nom d\'enfant. Quand il se proclame adulte, l\'elfe se choisit un nom d\'adulte. Tout elfe porte également un nom de famille qui se compose habituellement d\'une combinaison de mots elfiques. Une partie des elfes qui voyagent parmi les humains le traduisent en commun.</p><p><strong>Les noms d\'enfant.</strong> Ara, Bryn, Del, Innil, Lael, Mella, Naéris, Phann, Rael, Rinn, Syllin, Vall.</p><p><strong>Les noms d\'adulte masculins.</strong> Adran, Berrian, Carric, Erevan, Galinndan, Hadaraï, Immeral, Paelias, Quarion, Riardon, Soveliss, Théren, Varis.</p><p><strong>Les noms d\'adulte féminins.</strong> Althaéa, Béthrynne, Caélynn, Iélénia, Leshanna, Meriele, Naivara, Quillathe, Silaqui, Thia, Vadania, Valanthe, Xanaphie.</p><p><strong>Les noms de famille.</strong> (traduction en commun). Amastacie (Fleurstellaire), Galanodel (Murmurelunaire), Ilphelkiir (Boutondegemme), Liadon (Feuilleargent), Méliamne (Pieddechêne), Siannodel (Ruisseaulunaire).</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Halfelin',
            'description' => '<p>La plupart des halfelins n\'ont qu\'un objectif dans la vie : profiter du confort de leur foyer. Ils aiment vivre dans un endroit paisible, loin des monstres en maraude et du fracas des armées, en appréciant un feu ronflant dans la cheminée, un repas copieux, un bon verre et une conversation agréable.</p><p>Certains halfelins passent leur vie dans une communauté agricole isolée, mais d\'autres mènent une vie de nomades et voyagent constamment en groupe, attirés par la route et les grands horizons, impatients de découvrir de nouvelles terres et de nouvelles personnes. Mais même ces nomades aiment la paix, la bonne chère, le confort et un chez-soi douillet, même s\'il s\'agit d\'une roulotte qui cahote sur une route poussiéreuse.</p><p>Les halfelins à la taille si réduite parviennent à survivre dans un monde plein de créatures de plus grande taille en évitant de se faire remarquer ou, à défaut, en évitant d\'importuner autrui. Comme ils mesurent un peu moins d\'un mètre, ils semblent relativement inoffensifs, cela fait donc des siècles qu\'ils survivent dans l\'ombre des empires, en marge des guerres et des querelles politiques. Ils se concentrent sur leurs besoins basiques et apprécient les plaisirs simples, délaissant tout ce qui tient de l\'ostentatoire.</p><p>Les halfelins dont des gens affables et enthousiastes. Ils accordent une grande importance à leur famille et leurs amis, ainsi qu\'au confort de leur foyer et rêvent rarement de gloire. Les aventuriers de cette race parcourent généralement le monde par amitié, soif de voyages, curiosité ou dans l\'intérêt de leur communauté.',
            'example_surname' => '<p>Un halfelin a un prénom, un nom de famille et parfois un surnom. Le nom de famille est souvent un surnom si tenace qu\'il s\'est transmis d\'une génération à l\'autre.</p><p><strong>Les noms masculins.</strong> Alton, Andre, Cade, Corrin, Eldon, Errich, Finan, Garret, Lindal, Lyle, Merric, Milo, Osborn, Perrin, Reed, Roscoe, Wellby.</p><p><strong>Les noms féminins.</strong> Andry, Bree, Callie, Cora, Euphémie, Jillian, Kithri, Lavinia, Lidda, Merla, Nedda, Paèle, Portia, Seraphine, Shaena, Trym, Vani, Verna.</p><p><strong>Les noms de famille.</strong> Bontonneau, Buisson, Butepavé, Épine, Feuilledethé, Grandpré, Hautecolline, Récoltepinceaux, Roulecolline, Vertbouteille.</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Humain',
            'description' => '<p>Les humains forment la plus jeune des races communes. Ils sont arrivés tardivement sur la scène mondiale et leur vie est bien courte par rapport à celle des nains, des elfes et des dragons. Cependant, ils sont les plus novateurs, n\'hésitent pas à relever des défis et sont les pionniers de ce monde, sans compter qu\'ils sont plus adaptables et ambitieux que les membres des autres races.</p><p>Quand les humains s\'installent, c\'est pour longtemps : ils construisent des villes conçues pour résister au passage du temps et de grands royaumes capables de survivre pendant des siècles. Ils vivent pleinement dans le présent, en quoi ils sont parfaitement adaptés à la vie d\'aventurier, mais ils anticipent également l\'avenir et cherchent à laisser un héritage pérenne.</p><p>La culture humaine varie en fonction des régions. La mode, l\'architecture, la cuisine, la musique et la littérature change en fonctions des contrées,villes et même au seins des quartiers d\'une même ville. Les caractéristiques physiques des humains varient en fonction des migrations des premiers membres de leur espèce, à tel point que les habitants des grandes villes présentent tous les types de carnation et signes particuliers possibles.</p>',
            'example_surname' => '<p>Comme la race humaine possède bien plus de cultures différentes que les autres, les humains n\'ont pas de noms typiques. Certains parents donnent des noms étrangers à leurs enfants, par exemple tirés du nain ou de l\'elfique (et prononcés plus ou moins correctement). Les noms traditionnels des humains varient donc énormément d\'une culture à l\'autre. On trouve ainsi des noms comme Haseid (calishite), Kerri (chondathien), Kosef (damarien), Amafrey (illuskien), So-Kehur (mulien), Madislak (rashémi), Mei (shou), ou Salazar (turami).</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Nain',
            'description' => '<p>Des royaumes riches d\'une antique splendeur, des salles taillées dans les racines des montagnes, l\'écho des pioches et des marteaux dans les profondeurs des mines et au cœur des forges aux flammes crépitantes, un engagement envers le clan et les traditions, une haine farouche envers les gobelins et les orcs… Voici les traits communs à tous les nains.</p><p>Les nains sont des êtres courageux et résistants, connus pour leurs talents de guerriers, de mineurs et de travailleurs de la pierre et du métal. Ils peuvent vivre près de 400 ans, les plus âgés se souviennent donc souvent d\'un monde bien différent de l\'actuel.</p><p>Les nains sont aussi solides que résistants que les montagnes qu\'ils aiment, supportant le passage des siècles avec endurance et stoïcisme, sans changer. Un nain est loyal et déterminé, fidèle à sa parole et résolu dans ses actes, parfois au point de se comporter avec obstination.</p>',
            'example_surname' => '<p>Le nain reçoit son nom d\'un aîné du clan, en accord avec la tradition. Un nom respectable a été utilisé et réutilisé maintes fois au fil des générations. Le nom d\'un nain appartient au clan, pas à l\'individu. Un nain qui fait mauvais usage de son nom ou fait honte au nom de son clan en est privé et a interdiction formelle d\'utiliser un autre nom nain à la place.</p><p><strong>Les noms masculins.</strong> Adrik, Albérich, Baern, Barendd, Brottor, Bruenor, Dain, Darrak, Delg, Eberk, Einkil, Fargrim, Flint, Gardain, Harbek, Kildrak, Morgran, Orsik, Oskar, Rangrim, Rurik, Taklinn, Thoradin, Thorin, Tordek, Traubon, Travok, Ulfgar, Veit, Vondal.</p><p><strong>Les noms féminins.</strong> Ambre, Artin, Audhild, Bardryn, Dagnal, Diesa, Eldeth, Falkrunn, Finellen, Gunnloda, Gurdis, Helja, Hlin, Kathra, Kristryd, Ilde, Liftrasa, Mardred, Riswynn, Sannl, Torbera, Torgga, Vistra.</p><p><strong>Les noms de clan.</strong> Barbegelée, Dankil, Fortenclume, Gorunn, Loderr, Marteaudeguerre, Poingdefer, Strakeln, Torunn, Ungart.</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Demi-Elfe',
            'description' => '<p>Issus de deux mondes sans vraiment appartenir à aucun, les demi-elfes combinent ce que certains disent être les meilleures qualités de leurs parents humains et elfes : la curiosité, l\'inventivité et l\'ambition des humains, tempérées par le sens du raffinement, l\'amour de la nature et les goûts artistiques des elfes. Certains demi-elfes vivent parmi les humains, mis à l\'écart à cause de leurs différences émotionnelles et physiques, condamnés à voir ceux qu\'ils aiment vieillir alors que le temps les effleure à peine. D\'autres vivent avec les elfes et se laissent gagner par la fébrilité quand ils atteignent l\'âge adulte dans les royaumes intemporels des elfes où leurs camarades continuent de vivre comme des enfants. De nombreux demi-elfes se révèlent incapables de s\'intégrer pleinement dans la société d\'un de leurs parents et optent pour une vie de vagabondages solitaires ou rejoignent d\'autres marginaux et exilés pour mener une vie d\'aventures.</p><p>Les demi-elfes n\'ont pas de terres, même s\'ils sont les bienvenus dans les villes humaines et tolérés dans les forêts elfiques. Dans les grandes villes des régions où les elfes et les humains interagissent fréquemment, les demi-elfes sont parfois assez nombreux pour former de petites communautés. Ils apprécient la compagnie de leurs semblables, les seuls à même de comprendre à quel point il est difficile de vivre entre ces deux mondes.</p><p>Comme les elfes, ils ressentent le besoin de voyager né de leur grande longévité. D\'autres, au contraire, se jettent à corps perdu dans le flot de la société et mettent leur charisme et leurs compétences sociales à profit pour devenir d\'excellents diplomates ou de parfaits escrocs.</p>',
            'example_surname' => '<p>Les demi-elfes utilisent les conventions baptismales des elfes ou des humains. Comme pour accentuer le fait qu\'ils n\'appartiennent pas entièrement à leurs communautés parentes, les demi-elfes nés parmi les humains reçoivent souvent un nom elfique tandis que ceux qui naissent chez les elfes héritent d\'un nom humain. Voici quelques exemples de noms d\'elfes :</p><p><strong>Les noms d\'enfant.</strong> Ara, Bryn, Del, Innil, Lael, Mella, Naéris, Phann, Rael, Rinn, Syllin, Vall.</p><p><strong>Les noms d\'adulte masculins.</strong> Adran, Berrian, Carric, Erevan, Galinndan, Hadaraï, Immeral, Paelias, Quarion, Riardon, Soveliss, Théren, Varis.</p><p><strong>Les noms d\'adulte féminins.</strong> Althaéa, Béthrynne, Caélynn, Iélénia, Leshanna, Meriele, Naivara, Quillathe, Silaqui, Thia, Vadania, Valanthe, Xanaphie.</p><p><strong>Les noms de famille.</strong> (traduction en commun). Amastacie (Fleurstellaire), Galanodel (Murmurelunaire), Ilphelkiir (Boutondegemme), Liadon (Feuilleargent), Méliamne (Pieddechêne), Siannodel (Ruisseaulunaire).</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Demi-Orc',
            'description' => '<p>Qu\'elles soient unies sous les ordres d\'un puissant sorcier ou qu\'elles se soient battues pendant des années jusqu\'à arriver à un statu quo, il arrive que des tribus orques et humaines forment une alliance et unissent leurs forces pour terroriser les contrées civilisées voisines. Et quand ces alliances sont scellées par un mariage, il naît des demi-orcs. Certains s\'élèvent au rang de puissant chef de clan, leur sang humain leur donnant un certain avantage sur leurs rivaux purement orcs. D\'autres sillonnent le monde afin de prouver leur valeur parmi les humains et les autres races plus civilisées. Nombre d\'entre ceux-là optent pour une carrière d\'aventurier. Ils atteignent la grandeur par leurs tours de force et la notoriété par leurs traditions barbares et leur férocité sauvage. </p><p>Les orcs tirent orgueil des cicatrices reçues au combat et considèrent les scarifications comme des ornements.Tout demi-orc qui a vécu un temps auprès des orcs porte des cicatrices; qu\'elles soient des marques d\'orgueil ou d\'humiliation, elles racontent ses exploits et ses blessures. Si un tel demi-orc vit ensuite parmi les humains, il peut exhiber fièrement ces balafres ou les cacher honteusement.</p><p>Les demi-orcs ressentent des émotions très puissantes. La rage ne se contente pas d\'accélérer leur pouls, elle embrase tout leur corps. Une insulte brûle comme de l\'acide et la tristesse sape leurs forces. Mais leur rire résonne clair et fort et les plaisirs physiques simples comme les festins, la lutte, les beuveries, la musique des tambours et les folles danses emplissent leur cœur de joie.</p>',
            'example_surname' => '<p>Les demi-orcs portent généralement des noms adaptés à la culture au sein de laquelle ils grandissent. Un demi-orc désireux de s\'intégrer chez les humains échange parfois un nom orc contre un nom humain. Certains demi-orcs aux noms humains décident au contraire d\'adopter un nom orc aux sonorités gutturales en pensant que cela les rendra plus intimidants.</p><p><strong>Les noms masculins.</strong> Dench, Feng, Gell, Henk, Holg, Imsh, Keth, Krusk, Mhurren, Ront, Shump, Thokk.</p><p><strong>Les noms féminins.</strong> Baggi, Émen, Engong, Kansif, Myev, Neega, Ovak, Ownka, Shautha, Sutha, Vola, Volen, Yevelda.</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Drakéide',
            'description' => '<p>Nés d\'un dragon, comme leur nom le proclame, les drakéide parcourent fièrement un monde qui les accueille avec une incompréhension mêlée de crainte. Façonnés par les dieux draconiques ou par les dragons eux-mêmes, les drakéide sont éclos d\'œufs de dragon afin de former une race unique, combinant le meilleur des dragons et des humanoïdes. Certains sont de fidèles serviteurs des véritables dragons, d\'autres forment la piétaille de grandes armées et d\'autres encore errent sans vocation.</p><p>Pour un drakéide, le clan revêt plus d\'importance que la vie elle-même. Chaque individu voue sa vie à son clan et lui accorde plus de respect et de dévotion qu\'à toute autre chose, plus qu\'aux dieux eux-mêmes. La conduite de chaque drakéide reflète l\'honneur de son clan et un individu qui déshonore son clan risque l\'exil. Chaque drakéide connaît son rang et ses devoirs au sein du clan, l\'honneur exigeant qu\'il respecte les limites de sa position.</p><p>Le sang d\'un certain type de dragon chante parfois puissamment au sein d\'un clan. Ses membres présentent alors des écailles à la couleur plus proche de celle de leur ancêtre rouge vif, vert, bleu, blanc ou d\'un noir lustré ou bien luisant d\'un éclat métallique aux reflets d\'or, d\'argent, de cuivre, d\'airain ou de bronze.</p>',
            'example_surname' => '<p>Les drakéides reçoivent un prénom à la naissance, mais ils annoncent toujours le nom de leur clan en premier, en signe de respect. Entre eux, les enfants d\'une même couvée utilisent souvent un nom d\'enfant ou un surnom. Il s\'agit souvent d\'un terme descriptif ou affectueux, qui peut rappeler un événement ou être basé sur une habitude.</p><p><strong>Les noms masculins.</strong> Arjhan, Balasar, Bharash, Donaar, Ghesh, Heskan, Kriv, Medrash, Méhen, Nadarr, Pandjed, Patrin, Rhogar, Shamash, Shedinn, Tarhun, Torinn.</p><p><strong>Les noms féminins.</strong> Akra, Biri, Daar, Farideh, Harann, Havilar,Jheri, Kava, Korinn, Mishann, Nala, Perra, Raiann, Sora, Surina, Thava, Uadjit.</p><p><strong>Les noms d\'enfant.</strong> Grimpeur, Mordeur-de-Bouclier, PerceOreille, Dévot, Sauteur, Zélé.</p><p><strong>Les noms de clan.</strong> Clethtinthiallor, Daardendrian, Delmirev, Drachedandion, Fenkenkabradon, Kepeshkmolik, Kerrhylon, Kimbatuul, Linxakasendalor, Myastan, Nemmonis, Norixius, Ophinshtalajiir, Prexijandilin, Shestendeliath, Turnuroth, Verthisathurgiesh, Yarjerit.</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Gnome',
            'description' => '<p>Un bourdonnement trahissant une activité débordante accompagne en permanence les écheveaux d\'habitations souterraines et les quartiers où les gnomes s\'installent en communautés très soudées. D\'autres sons couvrent ponctuellement ce bourdonnement perpétuel : le crissement d\'une broyeuse, une petite explosion, un cri de surprise ou de triomphe et surtout, surtout, des éclats de rire. Les gnomes se réjouissent de la vie et apprécient chaque minute passée à inventer quelque chose, à explorer, chercher, créer et jouer.</p><p>Pour les gnomes, le simple fait de vivre est une chose merveilleuse et ils veillent à tirer un maximum de joie de leurs trois à cinq siècles d\'existence. Les humains craindraient de s\'ennuyer avec une espérance de vie aussi longue, les elfes prennent leur temps pour savourer toutes les beautés du monde au fil de leur longue vie, mais les gnomes, eux, ont peur de ne pas avoir le temps de faire et voir tout ce qu\'ils veulent malgré leur existence prolongée.</p><p>Un gnome parle comme s\'il n\'arrivait pas à transmettre ses idées assez vite à son goût. Mais même quand il propose ses idées et donne son opinion sur un sujet, il parvient à écouter attentivement les autres et ajoute les exclamations de surprise ou d\'approbation appropriées pendant le dialogue.</p><p>Les gnomes aiment les plaisanteries en tout genre, en particulier les jeux de mots et les farces, mais ils sont tout à fait capables de se concentrer sur une tâche sérieuse dès qu\'ils en entament une. Nombre de gnomes sont des ingénieurs, des alchimistes, des bricoleurs et des inventeurs de talent. Ils acceptent de faire des erreurs et rient d\'eux-mêmes afin de perfectionner leur art, en prenant des risques courageux (voire téméraires) et n\'hésitent pas à voir les choses en grand.</p>',
            'example_surname' => '<p>Les gnomes adorent les noms et ils en ont tous une demidouzaine. La mère du gnome, son père, l\'aîné de son clan, ses tantes, ses oncles ... Tous lui donnent un nom et il peut même adopter les surnoms que les gens lui donnent au fil du temps. Les noms des gnomes se déclinent généralement sur ceux de leurs ancêtres ou parents éloignés, mais certains sont de pures inventions. Quand un gnome a affaire à un humain ou toute autre personne très « collet monté » à propos des noms, il se limite généralement à trois noms : un nom personnel, un nom de clan et un surnom, en choisissant dans chaque catégorie celui qu\'il trouve le plus drôle à annoncer.</p><p><strong>Les noms masculins.</strong> Alston, Alvyn, Boddynock, Brocc, Burgell, Dimble, Eldon, Erky, Fonkin, Frug, Gerbo, Gimble, Glim,Jebeddo, Kellen, Namfoodle, Orryn, Roondar, Seebo, Sindri, Warryn, Wrenn, Zook.</p><p><strong>Les noms féminins.</strong> Bimpnottine, Breena, Caramip, Carline, Donella, Duvamil, Ella, Ellyjobell, Ellywick, Lilli, Loopmottine, Lorilla, Mardnab, Nissa, Nyx, Oda, Orla, Roywyn, Shamil, Tana, Waywocket, Zanna.</p><p><strong>Les noms de clan.</strong> Beren, Daergel, Folkor, Garrick, Nackle, Murnig, Ningel, Raulnor, Scheppen, Timbers, Turen.</p><p><strong>Les surnoms.</strong> Brillegemme, Canardboiteux, Cendrefoyer, Clapebière, Doubleboucle, Fnipper, Furet, Ku, Manteau, Nim, Piquepâte, Pock, Qu\'unechaussure.</p>'
        ]);
        Race::insert([
            'id' => Str::uuid(),
            'name' => 'Tieffelin',
            'description' => '<p>Être accueilli par des regards appuyés et des murmures, subir des insultes et des démonstrations de violence dans la rue, lire la méfiance et la peur dans les yeux de chacun, voilà le lot des tieffelins. Et pour ne rien arranger, ils savent tous qu\'ils souffrent de ce comportement à cause d\'un pacte conclu il y a des générations de cela, grâce auquel Asmodée, le seigneur suprême des Neuf Enfers, a imprégné leur lignée de son essence. Ils ne sont pas coupables de leur apparence ni de leur nature, pourtant elles découlent d\'un péché antique pour lequel eux-mêmes, leurs enfants et les enfants de leurs enfants seront à jamais tenus responsables.</p><p>Les tieffelins survivent en petites minorités, principalement dans les villes humaines où ils grandissent dans les quartiers  les plus mal famés et deviennent escrocs, voleurs ou seigneurs du crime. Ils vivent parfois parmi d\'autres minorités, dans des enclaves où ils sont traités avec un peu plus de respect.</p><p>Les gens ont tendance à se méfier des tieffelins, car ils se disent que leur héritage infernal a sûrement souillé leur personnalité et leur moralité en plus de leur apparence. Quand un tieffelin pénètre dans une boutique, le marchand surveille étroitement ses produits ; quand il arrive en ville, la garde le suit de loin pendant quelque temps et les démagogues le tiennent pour responsable de tout ce qui peut se produire d\'étrange. En réalité, l\'héritage des tieffelins n\'affecte pas vraiment leur personnalité ; en revanche, les années passées à endurer la méfiance d\'autrui marquent tous les tieffelins et chacun réagit à sa manière. Certains décident de se conformer au stéréotype malveillant que les gens ont d\'eux, d\'autres sont naturellement vertueux. La plupart sont juste pleinement conscients de la manière dont les gens réagissent à leur vue et, après avoir enduré leur méfiance pendant toute leur jeunesse, ils apprennent souvent à surmonter les préjugés en usant de leur charme ou en recourant à l\'intimidation.</p>',
            'example_surname' => '<p>Les noms des tieffelins se divisent en trois catégories. Un tieffelin né au sein d\'une culture donnée reçoit souvent un nom issu de cette culture, tandis que d\'autres portent des noms dérivés de l\'infernal et transmis de génération en génération pour refléter leur héritage diabolique. Enfin, quelques jeunes tieffelins cherchant à gagner leur place dans le monde adoptent un nom représentant une vertu ou un autre concept et tentent de l\'incarner au mieux. Pour certains, le nom choisi est une noble quête, pour d\'autres, c\'est une sinistre destinée.</p><p><strong>Les noms infernaux masculins.</strong> Akménos, Amnon, Barakas, Damakos, Ékemon, !ados, Kairon, Leucis, Melech, Mordaï, Morthos, Pelaïos, Skamos, Théraï.</p><p><strong>Les noms infernaux féminins.</strong> Akta, Anakis, Bryséis, Criella, Damaïa, Éa, Kallista, Lérissa, Makarie, Néméïa, Orianna, Phélaïa, Rieta.</p><p><strong>Les noms de «vertu».</strong> Art, Chagrin, Chant, Charogne, Credo, Désespoir, Espoir, Excellence, Gloire, Hasard, Idéal, Lassitude, Musique, Nulle-Part, Ouverture, Poésie, Quête, Révérence, Témérité, Terreur, Tourment.</p>'
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('races');
    }
};
